### ISSUE TITLE
Redstone Dust, After Being Mined, Doesn't Get Picked Up Immediately Like Every Other Block/Item Mined

### ISSUE THREAD

**Issue by DizzyDJW** [misterplus/Levitated#54] opened 2020-09-28 03:39 UTC
## Bug Description
Whenever Redstone Ore is mined in the End, the redstone dust stays on the ground at the feet of the player for 3-5x longer than other blocks/items before being picked up.

### Did this behavior use to work in the previous version?
I don't know

## Steps to Reproduce (for bugs)
1. Mine Redstone Ore in the End.
2. Watch Redstone Dust.

## Logs
No logs, no crash

## Client Information
* Modpack Version: 1.4.1
* Java Version: Ver. 8 Update 261
* Launcher Used: Minecraft
* Memory Allocated: 8192MB
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 1.4.1
* Additional Content Installed: None

**Comment by misterplus** [comment] 2020-09-28 04:34
This is caused by a bad implementation in Wizardry. Already fixed in the next version.

**Closed** 2020-09-28 04:34 UTC
Labels: Bug: To be fixed
