### ISSUE TITLE
Replace Immersive Tech with Immersive Technology

### ISSUE THREAD

**Issue by chriptus13** [misterplus/Levitated#53] opened 2020-09-25 20:03 UTC
## Bug Description
Same error has https://github.com/FerroO2000/Immersive-Tech/issues/101

### Did this behavior use to work in the previous version?
First version that I'm using

## Steps to Reproduce (for bugs)
1. Run ServerStart script

## Logs

* Client/Server Log:
```
[20:47:18] [Server thread/ERROR] [FML]: Error registering event handler: FMLMod:immersivepetroleum{1.1.9} class blusunrize.immersiveengineering.api.MultiblockHandler$MultiblockFormEvent public void flaxbeard.immersivepetroleum.common.items.ItemProjector.handleMultiblockComplete(blusunrize.immersiveengineering.api.MultiblockHandler$MultiblockFormEvent)
java.lang.InstantiationException: null
        at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) ~[?:1.8.0_265]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_265]
        at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:130) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:112) [EventBus.class:?]
        at flaxbeard.immersivepetroleum.common.items.ItemProjector.<init>(ItemProjector.java:73) [ItemProjector.class:?]
        at flaxbeard.immersivepetroleum.common.IPContent.preInit(IPContent.java:146) [IPContent.class:?]
        at flaxbeard.immersivepetroleum.ImmersivePetroleum.preInit(ImmersivePetroleum.java:55) [ImmersivePetroleum.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.redirect$zza000$forgeImpl$PostEvent(LoadController.java:568) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
[20:47:19] [Server thread/ERROR] [immersiveengineering]: WireType#init was called by Immersive Tech (immersivetech)!
[20:47:19] [Server thread/ERROR] [immersiveengineering]: The method should only be called by Immersive Engineering, calls from other mods will cause many hard-to-debug issues and are therefore forbidden!
[20:47:19] [Server thread/ERROR] [immersiveengineering]: Please report this as a bug to Immersive Tech
```
* Crash Log: NA

## Client Information
* Modpack Version: 1.4.1
* Java Version: 1.8.0_265
* Launcher Used: NA
* Memory Allocated: 2048M
* Server/LAN/Single Player: Server
* Optifine Installed: NA
* Shaders Enabled: NA

## World Information
* Modpack Version world created in: 1.4.1
* Additional Content Installed: NA

**Comment by misterplus** [comment] 2020-09-26 01:54
I suggest try redownloading the server again, I can confirm the server pack is working.

**Comment by chriptus13** [comment] 2020-09-26 02:17
Ya server works just saw that error and wanted to report. Should I replace the mod?

**Comment by misterplus** [comment] 2020-09-26 02:37
Nope, it's already the latest version available on curseforge. If you don't have any more issues, consider closing this issue.

**Comment by chriptus13** [comment] 2020-09-26 03:23
I mean replacing it with https://www.curseforge.com/minecraft/mc-mods/mct-immersive-technology. Like mentioned in https://github.com/FerroO2000/Immersive-Tech/issues/101.

**Comment by misterplus** [comment] 2020-09-26 03:31
> I mean replacing it with https://www.curseforge.com/minecraft/mc-mods/mct-immersive-technology. Like mentioned in [FerroO2000/Immersive-Tech#101](https://github.com/FerroO2000/Immersive-Tech/issues/101).

Oh, that was unexpected. Didn't know that existed.
We'll look into it and if the compactibility is good, we'll replace it. Thanks for mentioning this.

**Comment by misterplus** [comment] 2020-10-16 11:40
Seems like Immersive Technology changed distilled water's liquid id, which makes previous saves incompatible, in a way.
So I reopened this issue to discuss that whether Immersive Technology should make it to ver1.5.1

**Comment by misterplus** [comment] 2020-10-17 08:19
After a discussion with other team members, we decided to go with Immersive Technology anyway, since losing distilled water for older saves won't be as a big deal.

**Closed by misterplus** 2020-10-17 08:19 UTC
Labels: Enhancement: New, Priority: Medium
